display_options:
  config_names:
    global_hash_table: Global Hash Table
    global_hash_table_compact: Global Hash Table (Compact)
    radix_trees: Radix Trees
    extent_trees: Extent Trees
    none: Baseline
    level_hash_tables: Level Hash Tables
    global_cuckoo_hash: "Global\nHash Table"
    global_cuckoo_hash_compact: Global Cuckoo Hash Table (Compact)
    hashfs: HashFS

  breakdown_names:
    indexing: Indexing
    indexing_per_op: Indexing
    read_data: Device IO
    read_data_per_op: Device IO

  benchmark_order:
    - 1MB
    - 64kB
    - 4kB

  config_colors:
    Global Hash Table: '#8dd3c7'
    Global Hash Table (Compact): '#FF0000'
    Radix Trees: '#ffffb3'
    Extent Trees: '#bebada'
    Level Hash Tables: '#fb8072'
    "Global\nHash Table": '#999999'
    Global Cuckoo Hash Table (Compact): '#990099'
    Baseline: '#ff0000'
    HashFS: '#34a1eb'

  config_order:
    - Global Hash Table
    - Global Hash Table (Compact)
    - Radix Trees
    - Extent Trees
    - Baseline
    - Level Hash Tables
    - "Global\nHash Table"
    - Global Cuckoo Hash Table (Compact)
    - HashFS

