display_options:
  config_names:
    global_hash_table: Global Hash Table
    global_hash_table_compact: Global Hash Table (Compact)
    radix_trees: Radix Trees
    extent_trees: Extent Trees
    none: Strata Baseline
    level_hash_tables: "Level\nHash Tables"
    global_cuckoo_hash: "Global\nHash Table"
    global_cuckoo_hash_compact: Global Cuckoo Hash Table (Compact)
    hashfs: HashFS

  breakdown_names:
    indexing: Indexing
    indexing_per_op: Indexing
    indexing_per_rep: Indexing
    indexing_throughput: Indexing
    read_data: Device IO
    read_data_per_op: Device IO
    read_data_per_rep: Device IO
    read_data_throughput: Device IO
    io_path_per_op: File System Overhead
    app_logic_per_op: Application Overhead

  benchmark_order:
    - 1MB
    - 64kB
    - 4kB

  config_colors:
    Global Hash Table: '#8dd3c7'
    Global Hash Table (Compact): '#FF0000'
    Radix Trees: '#ffffb3'
    Extent Trees: '#bebada'
    "Level\nHash Tables": '#fb8072'
    "Global\nHash Table": '#999999'
    Global Cuckoo Hash Table (Compact): '#990099'
    Strata Baseline: '#ff0000'
    HashFS: '#34a1eb'

  config_order:
    - Global Hash Table
    - Global Hash Table (Compact)
    - Radix Trees
    - Extent Trees
    - "Level\nHash Tables"
    - "Global\nHash Table"
    - Global Cuckoo Hash Table (Compact)
    - HashFS
    - Strata Baseline

